(* generated by dune *)

(** @canonical Rocq_owl_tactics_plugin.G_owl_tactics *)
module G_owl_tactics = Rocq_owl_tactics_plugin__G_owl_tactics

(** @canonical Rocq_owl_tactics_plugin.Owl_bridge *)
module Owl_bridge = Rocq_owl_tactics_plugin__Owl_bridge

(** @canonical Rocq_owl_tactics_plugin.Owl_tactic_core *)
module Owl_tactic_core = Rocq_owl_tactics_plugin__Owl_tactic_core
