lib: [
  "_build/install/default/lib/rocq-owl-tactics/META"
  "_build/install/default/lib/rocq-owl-tactics/dune-package"
  "_build/install/default/lib/rocq-owl-tactics/opam"
  "_build/install/default/lib/rocq-owl-tactics/plugin/g_owl_tactics.ml" {"plugin/g_owl_tactics.ml"}
  "_build/install/default/lib/rocq-owl-tactics/plugin/owl_bridge.ml" {"plugin/owl_bridge.ml"}
  "_build/install/default/lib/rocq-owl-tactics/plugin/owl_tactic_core.ml" {"plugin/owl_tactic_core.ml"}
  "_build/install/default/lib/rocq-owl-tactics/plugin/rocq_owl_tactics_plugin.a" {"plugin/rocq_owl_tactics_plugin.a"}
  "_build/install/default/lib/rocq-owl-tactics/plugin/rocq_owl_tactics_plugin.cmi" {"plugin/rocq_owl_tactics_plugin.cmi"}
  "_build/install/default/lib/rocq-owl-tactics/plugin/rocq_owl_tactics_plugin.cmt" {"plugin/rocq_owl_tactics_plugin.cmt"}
  "_build/install/default/lib/rocq-owl-tactics/plugin/rocq_owl_tactics_plugin.cmx" {"plugin/rocq_owl_tactics_plugin.cmx"}
  "_build/install/default/lib/rocq-owl-tactics/plugin/rocq_owl_tactics_plugin.cmxa" {"plugin/rocq_owl_tactics_plugin.cmxa"}
  "_build/install/default/lib/rocq-owl-tactics/plugin/rocq_owl_tactics_plugin.ml" {"plugin/rocq_owl_tactics_plugin.ml"}
  "_build/install/default/lib/rocq-owl-tactics/plugin/rocq_owl_tactics_plugin__G_owl_tactics.cmi" {"plugin/rocq_owl_tactics_plugin__G_owl_tactics.cmi"}
  "_build/install/default/lib/rocq-owl-tactics/plugin/rocq_owl_tactics_plugin__G_owl_tactics.cmt" {"plugin/rocq_owl_tactics_plugin__G_owl_tactics.cmt"}
  "_build/install/default/lib/rocq-owl-tactics/plugin/rocq_owl_tactics_plugin__G_owl_tactics.cmx" {"plugin/rocq_owl_tactics_plugin__G_owl_tactics.cmx"}
  "_build/install/default/lib/rocq-owl-tactics/plugin/rocq_owl_tactics_plugin__Owl_bridge.cmi" {"plugin/rocq_owl_tactics_plugin__Owl_bridge.cmi"}
  "_build/install/default/lib/rocq-owl-tactics/plugin/rocq_owl_tactics_plugin__Owl_bridge.cmt" {"plugin/rocq_owl_tactics_plugin__Owl_bridge.cmt"}
  "_build/install/default/lib/rocq-owl-tactics/plugin/rocq_owl_tactics_plugin__Owl_bridge.cmx" {"plugin/rocq_owl_tactics_plugin__Owl_bridge.cmx"}
  "_build/install/default/lib/rocq-owl-tactics/plugin/rocq_owl_tactics_plugin__Owl_tactic_core.cmi" {"plugin/rocq_owl_tactics_plugin__Owl_tactic_core.cmi"}
  "_build/install/default/lib/rocq-owl-tactics/plugin/rocq_owl_tactics_plugin__Owl_tactic_core.cmt" {"plugin/rocq_owl_tactics_plugin__Owl_tactic_core.cmt"}
  "_build/install/default/lib/rocq-owl-tactics/plugin/rocq_owl_tactics_plugin__Owl_tactic_core.cmx" {"plugin/rocq_owl_tactics_plugin__Owl_tactic_core.cmx"}
]
libexec: [
  "_build/install/default/lib/rocq-owl-tactics/plugin/rocq_owl_tactics_plugin.cmxs" {"plugin/rocq_owl_tactics_plugin.cmxs"}
]
bin: [
  "_build/install/default/bin/rocq-owl-tactics.owl-smoke"
]
doc: [
  "_build/install/default/doc/rocq-owl-tactics/README.md"
]
